[tool.poetry]
name = "TDS-DATA-ANALYST"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.12.*"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
